# Generated by Django 2.2.17 on 2020-12-16 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('center', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('time', models.TextField(blank=True, default={}, null=True)),
                ('range', models.TextField(blank=True, default=[], null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gallery_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
        ),
    ]
